/**
 * This file is part of Sita Team Decompiler.
 *
 * Sita Team Decompiler is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 *
 * Sita Team Decompiler is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Sita Team Decompiler. If not, see
 * <https://www.gnu.org/licenses/>.
 */

#ifdef TDx64
#define tagPERMSYM        tagPERMSYM64
#define StringTable       StringTable64
#define tagITEM           tagITEM64
#define tagOSEG           tagOSEG64
#define HandTable         HandTable64
#define SymbolHash        SymbolHash64
#define HItem             HItem64
#define tagHEAPBLK        tagHEAPBLK64
#define Outline           Outline64
#define COutline          COutline64
#define Item              Item64
#define CItem             CItem64
#define CVar              CVar64
#define CVarScope         CVarScope64
#define CGlobalDecs       CGlobalDecs64
#define CClass            CClass64
#define CObject           CObject64
#define CDlg              CDlg64
#define CCase             CCase64
#define COn               COn64
#define CStatement        CStatement64
#define CString           CString64
#define CBoolean          CBoolean64
#define CDateTime         CDateTime64
#define CNumber           CNumber64
#define CFunctionalVar    CFunctionalVar64
#define COutlineVersion   COutlineVersion64
#define CClassDefinitions CClassDefinitions64
#define CLoop             CLoop64
#define CBreak            CBreak64
#define tag_items         tag_items64
#define item_bodies       item_bodies64
#define DecompileInfo     DecompileInfo64
#define DispatchFunction  DispatchFunction64
#define tagEXFUNINFO      tagEXFUNINFO64
#define tagINTFUNHITEMS   tagINTFUNHITEMS64
#endif
