/**
 * This file is part of Sita Team Decompiler.
 *
 * Sita Team Decompiler is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 *
 * Sita Team Decompiler is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Sita Team Decompiler. If not, see
 * <https://www.gnu.org/licenses/>.
 */


#undef  tagPERMSYM
#undef  StringTable
#undef  tagITEM
#undef  tagOSEG
#undef  HandTable
#undef  SymbolHash
#undef  HItem
#undef  tagHEAPBLK
#undef  Outline
#undef  COutline
#undef  Item
#undef  CItem
#undef  CVar
#undef  CVarScope
#undef  CGlobalDecs
#undef  CClass
#undef  CObject
#undef  CDlg
#undef  CCase
#undef  COn
#undef  CStatement
#undef  CString
#undef  CBoolean
#undef  CDateTime
#undef  CNumber
#undef  CFunctionalVar
#undef  COutlineVersion
#undef  CClassDefinitions
#undef  CLoop
#undef  CBreak
#undef  tag_items
#undef  item_bodies
#undef  DecompileInfo
#undef  DispatchFunction
#undef  tagEXFUNINFO
#undef  tagINTFUNHITEMS
